/**
 * Monitoring visit edit page.
 *
 * Two URL shapes:
 *   /enterprises/:id/monitoring-visits/new           → new visit, client-side UUID
 *   /enterprises/:id/monitoring-visits/:visitId      → existing visit
 *
 * The visit's UUID is generated by the client on /new so the same id is used
 * across draft saves and the final submit click — meaning the offline queue
 * can replay an arbitrary sequence of edits to one visit without conflict.
 *
 * No approval workflow (status only flips draft → submitted). Submitted
 * visits stay editable to the same role (it's a record, not a gate). If
 * you want stricter rules later, add a CHECK or a transition payload.
 */
import { useEffect, useMemo, useRef, useState, type ChangeEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { useAuth } from '@/lib/auth';
import { useEnterprise } from '@/lib/enterprises';
import {
  useMonitoringVisit,
  useSaveMonitoringVisit,
  useMonitoringVisitPhotos,
  useUploadMonitoringVisitPhoto,
  useDeleteMonitoringVisitPhoto,
  usePendingVisitPhotos,
  useDiscardPendingPhoto,
  signedPhotoUrl,
} from '@/lib/monitoring-visits';
import { useOnlineStatus } from '@/lib/online-status';
import { useUnsavedChangesGuard } from '@/lib/use-unsaved-changes-guard';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { StatusPill } from '@/components/ui/status-pill';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ArrowLeft, Save, Send, Crosshair, Camera, Trash2, ImageIcon, Loader2, CloudOff } from 'lucide-react';
import { formatDateDMY } from '@/lib/utils';
import type {
  MonitoringVisitRow,
  MonitoringEnterprisePhase,
  MonitoringVisitType,
  MonitoringVisitStatus,
} from '@/types/database';

type Tri = boolean | null;

interface Draft {
  visit_date: string;
  visit_type: MonitoringVisitType;
  enterprise_phase: MonitoringEnterprisePhase;
  conducted_by_name: string;
  owner_present: Tri;
  others_present: string;
  signal_activity_on_track: Tri;
  signal_inputs_supplied: Tri;
  signal_records_maintained: Tri;
  signal_site_safe: Tri;
  signal_major_issues: Tri;
  observations: string;
  issues_noted: string;
  actions_agreed: string;
  actions_due_date: string;
  next_visit_planned: string;
  weather: string;
  gps_lat: string;
  gps_lng: string;
}

const EMPTY_DRAFT: Draft = {
  visit_date: new Date().toISOString().slice(0, 10),
  visit_type: 'routine',
  enterprise_phase: 'unknown',
  conducted_by_name: '',
  owner_present: null,
  others_present: '',
  signal_activity_on_track: null,
  signal_inputs_supplied: null,
  signal_records_maintained: null,
  signal_site_safe: null,
  signal_major_issues: null,
  observations: '',
  issues_noted: '',
  actions_agreed: '',
  actions_due_date: '',
  next_visit_planned: '',
  weather: '',
  gps_lat: '',
  gps_lng: '',
};

function hydrateFromRow(row: MonitoringVisitRow): Draft {
  return {
    visit_date: row.visit_date,
    visit_type: row.visit_type,
    enterprise_phase: row.enterprise_phase,
    conducted_by_name: row.conducted_by_name,
    owner_present: row.owner_present,
    others_present: row.others_present ?? '',
    signal_activity_on_track: row.signal_activity_on_track,
    signal_inputs_supplied: row.signal_inputs_supplied,
    signal_records_maintained: row.signal_records_maintained,
    signal_site_safe: row.signal_site_safe,
    signal_major_issues: row.signal_major_issues,
    observations: row.observations ?? '',
    issues_noted: row.issues_noted ?? '',
    actions_agreed: row.actions_agreed ?? '',
    actions_due_date: row.actions_due_date ?? '',
    next_visit_planned: row.next_visit_planned ?? '',
    weather: row.weather ?? '',
    gps_lat: row.gps_lat != null ? String(row.gps_lat) : '',
    gps_lng: row.gps_lng != null ? String(row.gps_lng) : '',
  };
}

/**
 * Build a patch with ONLY the keys we want to send. Strings get null-coalesced
 * to null for nullable columns so the server clears values when the user wipes
 * a field.
 */
function buildPatch(d: Draft): Record<string, unknown> {
  const numOrNull = (s: string) => (s.trim() === '' ? null : Number(s));
  return {
    visit_date: d.visit_date,
    visit_type: d.visit_type,
    enterprise_phase: d.enterprise_phase,
    conducted_by_name: d.conducted_by_name,
    owner_present: d.owner_present,
    others_present: d.others_present || null,
    signal_activity_on_track: d.signal_activity_on_track,
    signal_inputs_supplied: d.signal_inputs_supplied,
    signal_records_maintained: d.signal_records_maintained,
    signal_site_safe: d.signal_site_safe,
    signal_major_issues: d.signal_major_issues,
    observations: d.observations || null,
    issues_noted: d.issues_noted || null,
    actions_agreed: d.actions_agreed || null,
    actions_due_date: d.actions_due_date || null,
    next_visit_planned: d.next_visit_planned || null,
    weather: d.weather || null,
    gps_lat: numOrNull(d.gps_lat),
    gps_lng: numOrNull(d.gps_lng),
  };
}

/**
 * Yes / No / N-A tri-state toggle. Stored as boolean | null so the column
 * type matches the underlying DB. "Not assessed" is null.
 */
function TriPill({
  value,
  onChange,
  disabled,
}: {
  value: Tri;
  onChange: (v: Tri) => void;
  disabled?: boolean;
}) {
  return (
    <div className="flex gap-1.5">
      <StatusPill
        tone="success"
        active={value === true}
        disabled={disabled}
        onSelect={() => onChange(value === true ? null : true)}
      >
        Yes
      </StatusPill>
      <StatusPill
        tone="destructive"
        active={value === false}
        disabled={disabled}
        onSelect={() => onChange(value === false ? null : false)}
      >
        No
      </StatusPill>
    </div>
  );
}

function newVisitId(): string {
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) return crypto.randomUUID();
  // Fallback for very old browsers — unlikely in this codebase but safe.
  return `${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

export function MonitoringVisitEditPage() {
  const { id: enterpriseId, visitId: visitIdParam } = useParams<{ id: string; visitId?: string }>();
  const navigate = useNavigate();
  const { user } = useAuth();
  const online = useOnlineStatus();
  const isOffline = online === 'offline';

  // For a brand-new visit, we generate the id eagerly so subsequent draft
  // saves land on the same row. useMemo keeps it stable across re-renders.
  const visitId = useMemo(() => visitIdParam ?? newVisitId(), [visitIdParam]);
  const isNew = !visitIdParam;

  const { data: enterprise } = useEnterprise(enterpriseId);
  const existing = useMonitoringVisit(isNew ? undefined : visitId);
  const saveVisit = useSaveMonitoringVisit();
  const photos = useMonitoringVisitPhotos(visitId);
  const uploadPhoto = useUploadMonitoringVisitPhoto(visitId, enterpriseId ?? '');
  const deletePhoto = useDeleteMonitoringVisitPhoto();
  const pendingPhotos = usePendingVisitPhotos(visitId);
  const discardPhoto = useDiscardPendingPhoto();

  const [draft, setDraft] = useState<Draft>(EMPTY_DRAFT);
  const [dirty, setDirty] = useState(false);
  // Track whether the visit row has been persisted at least once (existing
  // visits start true). Photos need the row to exist for the FK + RLS, so the
  // first photo on a brand-new visit auto-saves the draft first.
  const [savedOnce, setSavedOnce] = useState(!isNew);
  const [addingPhotos, setAddingPhotos] = useState(false);
  const cameraInputRef = useRef<HTMLInputElement>(null);
  const libraryInputRef = useRef<HTMLInputElement>(null);

  // Guard browser-level + in-app navigation while there are unsaved edits.
  // Cleared on a successful save (setDirty(false) below in onSaveDraft /
  // onSubmit success branches).
  useUnsavedChangesGuard(
    dirty,
    'You have unsaved monitoring-visit edits — leave anyway?',
  );

  // Seed the visitor name from the logged-in user's email the first time.
  // The user can replace it with their full name on the form. (We don't pull
  // user_profiles here to keep the page snappy — the email is a reasonable
  // default for the field staff who fill these in.)
  useEffect(() => {
    if (isNew && !draft.conducted_by_name && user?.email) {
      setDraft((d) => ({ ...d, conducted_by_name: user.email ?? '' }));
    }
  }, [isNew, user?.email, draft.conducted_by_name]);

  // Hydrate when an existing visit loads.
  useEffect(() => {
    if (existing.data) {
      setDraft(hydrateFromRow(existing.data));
      setDirty(false);
    }
  }, [existing.data]);

  function set<K extends keyof Draft>(key: K, value: Draft[K]) {
    setDraft((d) => ({ ...d, [key]: value }));
    setDirty(true);
  }

  function onSaveDraft() {
    if (!enterpriseId) return;
    if (!draft.conducted_by_name.trim()) {
      toast.error('Enter your name (who conducted the visit)');
      return;
    }
    saveVisit.mutate(
      {
        visit_id: visitId,
        enterprise_id: enterpriseId,
        patch: { ...buildPatch(draft), conducted_by_user_id: user?.id ?? null },
        description: 'Save monitoring visit draft',
      },
      {
        onSuccess: (r) => {
          toast.success(r.online ? 'Visit saved' : 'Saved locally — will sync when online');
          setDirty(false);
          setSavedOnce(true);
          if (isNew) navigate(`/enterprises/${enterpriseId}/monitoring-visits/${visitId}`, { replace: true });
        },
        onError: (e: Error) => toast.error('Save failed', { description: e.message }),
      },
    );
  }

  /**
   * Make sure the visit row exists before attaching photos. On a brand-new
   * visit this saves the draft (online or offline) so the photo's FK + RLS
   * checks pass — and so the queued visit replays before the queued photos.
   */
  async function ensureVisitSaved(): Promise<boolean> {
    if (savedOnce) return true;
    if (!enterpriseId) return false;
    if (!draft.conducted_by_name.trim()) {
      toast.error('Enter your name (who conducted the visit) before adding photos');
      return false;
    }
    try {
      await saveVisit.mutateAsync({
        visit_id: visitId,
        enterprise_id: enterpriseId,
        patch: { ...buildPatch(draft), conducted_by_user_id: user?.id ?? null },
        description: 'Save monitoring visit draft',
      });
      setSavedOnce(true);
      setDirty(false);
      if (isNew) {
        navigate(`/enterprises/${enterpriseId}/monitoring-visits/${visitId}`, { replace: true });
      }
      return true;
    } catch (e) {
      toast.error('Could not save the visit', {
        description: e instanceof Error ? e.message : undefined,
      });
      return false;
    }
  }

  /**
   * Handle one or more picked/captured photos: ensure the visit exists, then
   * upload (online) or queue (offline) each file. Works for the single shot
   * from the camera and for a multi-select from the gallery.
   */
  async function handleFiles(files: File[]) {
    if (files.length === 0) return;
    setAddingPhotos(true);
    try {
      if (!(await ensureVisitSaved())) return;
      let uploaded = 0;
      let queued = 0;
      for (const file of files) {
        try {
          const r = await uploadPhoto.mutateAsync({ file });
          if (r.online) uploaded += 1;
          else queued += 1;
        } catch (e) {
          toast.error(`Couldn't add ${file.name || 'photo'}`, {
            description: e instanceof Error ? e.message : undefined,
          });
        }
      }
      if (uploaded > 0) toast.success(`${uploaded} photo${uploaded === 1 ? '' : 's'} uploaded`);
      if (queued > 0) {
        toast.success(
          `${queued} photo${queued === 1 ? '' : 's'} saved on this device — will upload when you're back online`,
        );
      }
    } finally {
      setAddingPhotos(false);
    }
  }

  function onPickFiles(e: ChangeEvent<HTMLInputElement>) {
    const files = Array.from(e.target.files ?? []);
    e.target.value = ''; // reset so picking the same file again re-fires onChange
    void handleFiles(files);
  }

  function onSubmit() {
    if (!enterpriseId) return;
    if (!draft.conducted_by_name.trim()) {
      toast.error('Enter your name (who conducted the visit)');
      return;
    }
    saveVisit.mutate(
      {
        visit_id: visitId,
        enterprise_id: enterpriseId,
        patch: { ...buildPatch(draft), conducted_by_user_id: user?.id ?? null },
        to_status: 'submitted',
        description: 'Submit monitoring visit',
      },
      {
        onSuccess: (r) => {
          toast.success(r.online ? 'Visit submitted' : 'Submit queued — will sync when online');
          setDirty(false);
          navigate(`/enterprises/${enterpriseId}?tab=monitoring`);
        },
        onError: (e: Error) => toast.error('Submit failed', { description: e.message }),
      },
    );
  }

  function captureGps() {
    if (!('geolocation' in navigator)) {
      toast.error('Geolocation is not supported on this device');
      return;
    }
    const id = toast.loading('Reading your location…');
    navigator.geolocation.getCurrentPosition(
      (pos) => {
        toast.dismiss(id);
        set('gps_lat', pos.coords.latitude.toFixed(6));
        set('gps_lng', pos.coords.longitude.toFixed(6));
        toast.success(`Captured ±${Math.round(pos.coords.accuracy)} m`);
      },
      (err) => {
        toast.dismiss(id);
        toast.error('Could not read location', { description: err.message });
      },
      { enableHighAccuracy: true, timeout: 15000, maximumAge: 0 },
    );
  }

  const submitted: MonitoringVisitStatus | undefined = existing.data?.status;

  return (
    <div className="space-y-6 max-w-3xl">
      {/* Header */}
      <div className="flex items-start justify-between gap-3 flex-wrap">
        <div>
          <Button asChild variant="ghost" size="sm" className="mb-1 -ml-2">
            <Link to={`/enterprises/${enterpriseId}?tab=monitoring`}>
              <ArrowLeft className="mr-1 h-3.5 w-3.5" /> Back to Monitoring
            </Link>
          </Button>
          <h1 className="text-2xl font-semibold tracking-tight">
            {isNew ? 'New monitoring visit' : 'Edit monitoring visit'}
          </h1>
          <p className="text-sm text-muted-foreground">
            {enterprise?.beneficiary_short_name ?? '…'} ·{' '}
            {formatDateDMY(draft.visit_date)}
          </p>
        </div>
        {submitted && (
          <Badge variant={submitted === 'submitted' ? 'default' : 'outline'}>{submitted}</Badge>
        )}
      </div>

      {/* Who + when + type */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Visit metadata</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-4 md:grid-cols-2">
          <div className="space-y-1.5">
            <Label htmlFor="visit_date">Visit date</Label>
            <Input
              id="visit_date"
              type="date"
              value={draft.visit_date}
              onChange={(e) => set('visit_date', e.target.value)}
            />
          </div>
          <div className="space-y-1.5">
            <Label>Visit type</Label>
            <Select value={draft.visit_type} onValueChange={(v) => set('visit_type', v as MonitoringVisitType)}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="routine">Routine</SelectItem>
                <SelectItem value="follow_up">Follow-up</SelectItem>
                <SelectItem value="complaint">Complaint</SelectItem>
                <SelectItem value="opportunistic">Opportunistic</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-1.5">
            <Label>Enterprise phase at this visit</Label>
            <Select
              value={draft.enterprise_phase}
              onValueChange={(v) => set('enterprise_phase', v as MonitoringEnterprisePhase)}
            >
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="pre_construction">Pre-construction</SelectItem>
                <SelectItem value="construction">Construction</SelectItem>
                <SelectItem value="operation">Operation</SelectItem>
                <SelectItem value="unknown">Unknown / N/A</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="conducted_by">Conducted by (your name)</Label>
            <Input
              id="conducted_by"
              value={draft.conducted_by_name}
              onChange={(e) => set('conducted_by_name', e.target.value)}
              placeholder="Field supervisor name"
            />
          </div>
        </CardContent>
      </Card>

      {/* Owner presence + quick signals */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Who was on site + quick signals</CardTitle>
          <CardDescription>
            Five quick yes/no checks that feed dashboard analytics over time. Leave blank
            if you didn't assess it on this visit.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-start justify-between gap-3 flex-wrap">
            <div>
              <div className="text-sm font-medium">Beneficiary / owner present?</div>
              <p className="text-xs text-muted-foreground">Who was there to walk you through the site.</p>
            </div>
            <TriPill value={draft.owner_present} onChange={(v) => set('owner_present', v)} />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="others_present">Others present (optional)</Label>
            <Input
              id="others_present"
              placeholder="e.g. spouse, RC officer, contractor"
              value={draft.others_present}
              onChange={(e) => set('others_present', e.target.value)}
            />
          </div>

          <div className="border-t pt-4 space-y-3">
            {[
              { key: 'signal_activity_on_track',  label: 'Activity progressing as planned' },
              { key: 'signal_inputs_supplied',    label: 'Equipment / inputs supplied as agreed' },
              { key: 'signal_records_maintained', label: 'Records / logs being maintained' },
              { key: 'signal_site_safe',          label: 'Site clean & safe' },
              { key: 'signal_major_issues',       label: 'Major issues observed' },
            ].map((row) => (
              <div key={row.key} className="flex items-center justify-between gap-3">
                <div className="text-sm">{row.label}</div>
                <TriPill
                  value={draft[row.key as keyof Draft] as Tri}
                  onChange={(v) => set(row.key as keyof Draft, v as never)}
                />
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Free-form observations + follow-up */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Observations</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="space-y-1.5">
            <Label htmlFor="observations">What did you see? (free-form)</Label>
            <Textarea
              id="observations"
              rows={4}
              placeholder="Activities under way, condition of equipment, signs of progress…"
              value={draft.observations}
              onChange={(e) => set('observations', e.target.value)}
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="issues_noted">Issues noted</Label>
            <Textarea
              id="issues_noted"
              rows={3}
              placeholder="Anything that needs escalating — delays, missing inputs, conflicts, weather damage…"
              value={draft.issues_noted}
              onChange={(e) => set('issues_noted', e.target.value)}
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="actions_agreed">Actions agreed</Label>
            <Textarea
              id="actions_agreed"
              rows={3}
              placeholder="What did you commit to do, what did the beneficiary commit to do?"
              value={draft.actions_agreed}
              onChange={(e) => set('actions_agreed', e.target.value)}
            />
          </div>
          <div className="grid gap-3 md:grid-cols-3">
            <div className="space-y-1.5">
              <Label htmlFor="actions_due_date">Actions due by</Label>
              <Input
                id="actions_due_date"
                type="date"
                value={draft.actions_due_date}
                onChange={(e) => set('actions_due_date', e.target.value)}
              />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="next_visit_planned">Next visit planned</Label>
              <Input
                id="next_visit_planned"
                type="date"
                value={draft.next_visit_planned}
                onChange={(e) => set('next_visit_planned', e.target.value)}
              />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="weather">Weather (optional)</Label>
              <Input
                id="weather"
                placeholder="e.g. sunny, heavy rain"
                value={draft.weather}
                onChange={(e) => set('weather', e.target.value)}
              />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* GPS */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">GPS coordinates</CardTitle>
          <CardDescription>Where on site you stood while filling this visit.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="flex justify-end">
            <Button type="button" size="sm" variant="outline" onClick={captureGps}>
              <Crosshair className="mr-1.5 h-3.5 w-3.5" /> Use my current location
            </Button>
          </div>
          <div className="grid gap-3 md:grid-cols-2">
            <div className="space-y-1.5">
              <Label htmlFor="gps_lat">Latitude (°)</Label>
              <Input
                id="gps_lat"
                type="number"
                step="0.000001"
                inputMode="decimal"
                placeholder="-29.310245"
                value={draft.gps_lat}
                onChange={(e) => set('gps_lat', e.target.value)}
              />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="gps_lng">Longitude (°)</Label>
              <Input
                id="gps_lng"
                type="number"
                step="0.000001"
                inputMode="decimal"
                placeholder="27.482167"
                value={draft.gps_lng}
                onChange={(e) => set('gps_lng', e.target.value)}
              />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Photos — works offline. Tapping "Take photo" opens the device camera
          (one shot at a time, so you can take several); "Add from device" lets
          you multi-select from the gallery. Offline captures are stored on the
          device and upload automatically on reconnect. */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <Camera className="h-4 w-4" /> Photos
          </CardTitle>
          <CardDescription>
            Take photos on site — works offline. Captured photos upload automatically when
            you're back on signal.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {/* Hidden inputs. `capture="environment"` asks the OS for the rear
              camera; the gallery input allows multi-select. */}
          <input
            ref={cameraInputRef}
            type="file"
            accept="image/*"
            capture="environment"
            className="hidden"
            onChange={onPickFiles}
          />
          <input
            ref={libraryInputRef}
            type="file"
            accept="image/*"
            multiple
            className="hidden"
            onChange={onPickFiles}
          />

          <div className="flex flex-wrap items-center gap-2">
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => cameraInputRef.current?.click()}
              disabled={addingPhotos}
            >
              <Camera className="mr-1.5 h-3.5 w-3.5" /> Take photo
            </Button>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => libraryInputRef.current?.click()}
              disabled={addingPhotos}
            >
              <ImageIcon className="mr-1.5 h-3.5 w-3.5" /> Add from device
            </Button>
            {addingPhotos && (
              <span className="inline-flex items-center gap-1.5 text-xs text-muted-foreground">
                <Loader2 className="h-3.5 w-3.5 animate-spin" /> Adding…
              </span>
            )}
          </div>

          {isOffline && (
            <p className="inline-flex items-center gap-1.5 text-xs text-muted-foreground">
              <CloudOff className="h-3.5 w-3.5" />
              You're offline — photos are saved on this device and upload when you reconnect.
            </p>
          )}

          {(pendingPhotos.length > 0 || (photos.data?.length ?? 0) > 0) && (
            <ul className="grid grid-cols-2 sm:grid-cols-3 gap-2">
              {/* Pending (offline) photos first — newest work on top. */}
              {pendingPhotos.map((p) => (
                <li
                  key={p.queueId}
                  className="relative group rounded-md overflow-hidden border bg-muted/30 aspect-square"
                >
                  <img src={p.url} alt="" className="absolute inset-0 w-full h-full object-cover" />
                  <span className="absolute inset-x-0 bottom-0 bg-foreground/60 text-[10px] text-background px-1.5 py-0.5 flex items-center gap-1">
                    <CloudOff className="h-3 w-3" /> Pending upload
                  </span>
                  <Button
                    variant="destructive"
                    size="icon"
                    className="absolute top-1 right-1 h-7 w-7 opacity-0 group-hover:opacity-100 focus-visible:opacity-100 transition"
                    onClick={() => {
                      if (!window.confirm('Discard this photo? It has not uploaded yet.')) return;
                      discardPhoto.mutate(
                        { queueId: p.queueId, blobKey: p.blobKey },
                        { onError: (e: Error) => toast.error('Could not discard', { description: e.message }) },
                      );
                    }}
                    title="Discard pending photo"
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                  </Button>
                </li>
              ))}
              {photos.data?.map((p) => (
                <PhotoTile
                  key={p.id}
                  storagePath={p.storage_path}
                  onDelete={() => {
                    if (!enterpriseId) return;
                    if (!window.confirm('Delete this photo?')) return;
                    deletePhoto.mutate(
                      { photo: p, enterprise_id: enterpriseId },
                      { onError: (e: Error) => toast.error('Delete failed', { description: e.message }) },
                    );
                  }}
                />
              ))}
            </ul>
          )}
        </CardContent>
      </Card>

      {/* Save / Submit actions — sticky on mobile so the user can finish
          filling, then tap Save/Submit without scrolling back up past the
          photo grid + GPS + 5 quick signals. Desktop keeps inline. */}
      <div className="sticky bottom-0 -mx-4 px-4 py-3 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/80 border-t z-10 flex items-center gap-2 flex-wrap
                      md:static md:mx-0 md:px-0 md:py-0 md:pt-2 md:bg-transparent md:backdrop-blur-none md:border-t-0">
        <Button onClick={onSaveDraft} disabled={saveVisit.isPending}>
          <Save className="mr-2 h-3.5 w-3.5" />
          {saveVisit.isPending ? 'Saving…' : 'Save draft'}
        </Button>
        <Button
          variant="outline"
          onClick={onSubmit}
          disabled={saveVisit.isPending || submitted === 'submitted'}
        >
          <Send className="mr-2 h-3.5 w-3.5" />
          {submitted === 'submitted' ? 'Already submitted' : 'Submit visit'}
        </Button>
        {dirty && <span className="text-xs text-warning">Unsaved changes</span>}
      </div>
    </div>
  );
}

/**
 * Thumbnail that signs a URL on mount. Photos sit in a private bucket so we
 * can't <img src=...> directly — sign each one for ~30 days.
 */
function PhotoTile({ storagePath, onDelete }: { storagePath: string; onDelete: () => void }) {
  const [url, setUrl] = useState<string | null>(null);
  useEffect(() => {
    let cancelled = false;
    signedPhotoUrl(storagePath).then((u) => {
      if (!cancelled) setUrl(u);
    });
    return () => {
      cancelled = true;
    };
  }, [storagePath]);
  return (
    <li className="relative group rounded-md overflow-hidden border bg-muted/30 aspect-square">
      {url ? (
        <img src={url} alt="" className="absolute inset-0 w-full h-full object-cover" loading="lazy" />
      ) : (
        <ImageIcon className="absolute inset-0 m-auto h-8 w-8 text-muted-foreground/40" />
      )}
      <Button
        variant="destructive"
        size="icon"
        className="absolute top-1 right-1 h-7 w-7 opacity-0 group-hover:opacity-100 focus-visible:opacity-100 transition"
        onClick={onDelete}
        title="Delete photo"
      >
        <Trash2 className="h-3.5 w-3.5" />
      </Button>
    </li>
  );
}
